name: Run every 5 minute

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron:
    name: Runs every 5 minutes
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world"
